"""Added models

Revision ID: a36c5f797a0f
Revises: 
Create Date: 2023-03-03 22:05:19.625344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36c5f797a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['correo'])

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['numero'])

    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('nivel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('maestro_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.alter_column('maestro_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nivel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('numero',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('correo',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
